### ISSUE TITLE
cant compile missing dragon.h

### ISSUE THREAD

**Issue by kablam** [Sinitronics/ThermoStatESP32#1]
hi im trying to test this out and when i try to upload it i get this:
hermoStatESP32:31:20: error: dragon.h: No such file or directory
compilation terminated.
exit status 1
dragon.h: No such file or directory

what am i missing?

**Comment by Sinitronics** [comment]
This is provided in the Adafruit_ILI9341 library: https://github.com/adafruit/Adafruit_ILI9341/tree/master/examples/pictureEmbed

You'll need to copy this to the main folder of the sketch or if you don't want the Welsh dragon on boot you can simply remove lines 31& 334. I'm probably going to completely re-write this anyway my coding skills are atrocious lol
